config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/user_guest', to: 'sessions#user_guest'
  post '/admin_guest', to: 'sessions#admin_guest'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :destinations, only: [:new, :index, :create, :edit, :update, :destroy]

  resources :cart_products, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      get :confirm
      get :thanks
    end
  end

  namespace :admin do
    get '/top', to: 'homes#top' 
    resources :products
    resources :users, only: [:index, :show, :edit, :update]
    patch '/admin/orders/:order_product_id', to: 'admin/orders#work_update'
    resources :orders,only: [:index, :show, :update] do
      member do
        patch :order_update
      end
    end
  end
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product

  with_options presence: true do
    validates :user_id
    validates :product_id
    validates :quantity
  end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :logged_in_user

  def index
    @cart_products = CartProduct.where(user_id: current_user.id)
    @categories = Category.where(is_valid: true)
    @areas = Area.all
  end

  def update
    @cart_products = CartProduct.find(params[:id])
    if @cart_products.update(cart_product_params)
      flash[:info] = '個数を変更しました'
      redirect_to cart_products_url
    else
      flash.now[:info] = '個数の変更に失敗しました'
      render :index
    end
  end

  def create
    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.user_id = current_user.id
    if @cart_product.save
      flash[:info] = '商品をカートに追加しました'
      redirect_to cart_products_url
    else
      flash[:info] = '個数を変更してください'
      redirect_to request.referer
    end
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    flash[:info] = '商品の削除が完了しました'
    redirect_to cart_products_url
  end

  def destroy_all
    user = User.find(current_user.id)
    if user.cart_products.destroy_all
      flash[:info] = 'カート内の商品を全て削除しました'
      redirect_to cart_products_url
    else
      flash.now[:info] = 'カート内の商品を削除できませんでした'
      render :index
    end
  end
  
  private

  def cart_product_params
    params.require(:cart_product).permit(:quantity, :price, :user_id, :product_id)
  end
  
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/index.html.erb
<div class="container">

<%= render 'layouts/flash' %>
  <% if current_user.cart_products.present? %>
  <br>
  <br>
  <div class="row">
    <div class="col-12">
      <h2>ショッピングカート</h2>
      <br>
      <br>
        <div class="btn-box text-right">
          <%= link_to "カートを空にする", destroy_all_cart_products_path, method: :delete, class:"btn btn-danger" %>
        </div>
        <br>
        <br>
        <table class="table">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cart_products.each do |cart_product| %>
            <tr>
              <td>
                <%= image_tag cart_product.product.image.url, :size => "100x75", class: "top-image" %>
                <%= cart_product.product.name %>
              </td>
              <td>
                <%= number_to_currency(cart_product.product.price_tax, :format => "%u%n", :unit => "￥", :precision => 0) %>(税込)
              </td>
              <td>
                <%= form_for(cart_product) do |f| %>
                  <%= f.number_field :quantity, min:1 %>
                  <%= f.submit "変更", class: "btn btn-primary" %>
                <% end %>
              </td>
              <td>
                <%= number_to_currency(cart_product.product.price_tax*cart_product.quantity, :format => "%u%n", :unit => "￥", :precision => 0) %>円
              </td>
              <td>
                <%= link_to "削除する", cart_product_path(cart_product.id), method: :delete, class: "btn btn-danger" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="text-right h3">
          合計:
          <%= number_to_currency(@cart_products.map{ |cp| (cp.product.price_tax*cp.quantity).round }.sum, 
          :format => "%u%n", :unit => "￥", :precision => 0) %>
        </div>
        <br>
        <br>
        <div class="col-xs-4 col-xs-offset-4">
          <%= link_to "買い物を続ける", products_path, class: "btn btn-primary" %>
          <br>
          <br>
          <%= link_to "情報入力に進む", new_order_path, class:"btn btn-success" %>
        </div>
        <br>
        <br>
        <br>
    </div>
  </div>
    

  <% else %>
  <div class="row">
    <div class="col-3">
      <%= render 'shared/sidebar', {categories: @categories, areas: @areas} %>
    </div>
  
    <div class="col-9">
      <h2>ショッピングカート</h2>
      <br>
      <div class="text-center"><%= link_to "まだカートに商品が入っていません！お買い物を楽しみましょう!", products_path, class: "btn btn-info" %></div>
    </div>
  </div>
  <% end %>


</div>