config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/user_guest', to: 'sessions#user_guest'
  post '/admin_guest', to: 'sessions#admin_guest'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :destinations, only: [:new, :index, :create, :edit, :update, :destroy]

  resources :cart_products, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      get :confirm
      get :thanks
    end
  end

  namespace :admin do
    get '/top', to: 'homes#top' 
    resources :products
    resources :users, only: [:index, :show, :edit, :update]
    patch '/admin/orders/:order_product_id', to: 'admin/orders#work_update'
    resources :orders,only: [:index, :show, :update] do
      member do
        patch :order_update
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  
  validates :first_name, presence: true, length: {maximum: 20}
  validates :last_name, presence: true, length: {maximum: 20}
  validates :first_name_kana, presence: true, length: {maximum: 20}, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :last_name_kana, presence: true, length: {maximum: 20}, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_roman, presence: true, length: {maximum: 30}, format: { with: /\A[A-Z]+\z/, message: 'は半角英大文字で入力して下さい。'}
  validates :last_name_roman, presence: true, length: {maximum: 30}, format: { with: /\A[A-Z]+\z/, message: 'は半角英大文字で入力して下さい。'}

  validates :birthday, presence: true

  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :prefecture_code, presence: true
  validates :address_city, presence: true, length: {maximum: 15}
  validates :address_street, presence: true, length: {maximum: 30}
  validates :address_building, length: {maximum: 30}

  validates :is_valid, inclusion: { in: [true, false] }

  VALID_ACCOUNT_REGEX = /\A[0-9a-z_]{1,15}\z/i
  validates :account_id, presence: true, length: {in: 6..15}, format: { with: VALID_ACCOUNT_REGEX }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :cart_products, dependent: :destroy
  has_many :destinations, dependent: :destroy
  has_many :orders

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def fullname
    last_name + first_name
  end

  def postcode_view
    self.postcode.to_s.insert(3, "-")
  end
  
  def fulladdress
    if self.address_building?
      "〒" + postcode_view + " " + prefecture_name + " " + address_city + " " + address_street + " " + address_building
    else
      "〒" + postcode_view + " " + prefecture_name + " " + address_city + " " + address_street
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :check_guest, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:account_id, :email, :password, :password_confirmation,
      :first_name, :last_name, :first_name_kana, :last_name_kana, :first_name_roman, :last_name_roman,
    :birthday, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :nickname, :is_valid)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:show, :edit, :update]
  before_action :check_guest, only: [:update]
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ONK Shoppingへようこそ!!"
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "登録情報を更新しました"
      redirect_to @user
    else
      flash.now[:danger] = '登録情報の更新に失敗しました'
      render 'edit'
    end
  end
  
  
  private

  def user_params
    params.require(:user).permit(:account_id, :email, :password, :password_confirmation,
      :first_name, :last_name, :first_name_kana, :last_name_kana, :first_name_roman, :last_name_roman,
    :birthday, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :nickname)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
              <%= form_for(@user) do |f| %>
                <%#= render 'shared/error_messages', object: f.object %>
                <div class="form-group">
                    <label for="account_id"><span class="badge badge-danger">必須</span> 会員ID</label>
                    <%= f.text_field :account_id, class: "form-control ", placeholder: "半角英数字6文字以上15字以内" %>
                </div>
                <div class="form-group">
                    <label for="email"><span class="badge badge-danger">必須</span> メールアドレス</label>
                    <%= f.email_field :email, class: "form-control ", placeholder: "例：raffaello@jungleocean.com" %>
                </div>
                <div class="form-group">
                    <label for="password"><span class="badge badge-danger">必須</span> パスワード</label>
                    <%= f.password_field :password, class: "form-control ", placeholder: "半角英数字6文字以上" %>
                </div>
                <div class="form-group">
                    <label for="password_confirmation"><span class="badge badge-danger">必須</span> パスワード(確認用)</label>
                    <%= f.password_field :password_confirmation, class: "form-control ", placeholder: "同じパスワードを再度入力してください" %>
                </div>
                <div class="form-group">
                    <label for="birthday"><span class="badge badge-danger">必須</span> 生年月日</label>
                    <%= f.date_field :birthday, class: "form-control ", placeholder: "例：1992/03/26", max: "9999-12-31" %>
                </div>

                <div class="row">
                  <div class="col">
                    <div class="form-group">
                        <label for="last_name"><span class="badge badge-danger">必須</span> 姓</label>
                        <%= f.text_field :last_name, class: "form-control ", placeholder: "例:山田" %>
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-group">
                        <label for="first_name"><span class="badge badge-danger">必須</span> 名</label>
                        <%= f.text_field :first_name, class: "form-control ", placeholder: "例:太郎" %>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col">
                    <div class="form-group">
                        <label for="last_name_kana"><span class="badge badge-danger">必須</span> セイ(フリガナ)</label>
                        <%= f.text_field :last_name_kana, class: "form-control ", placeholder: "例:ヤマダ" %>
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-group">
                        <label for="first_name_kana"><span class="badge badge-danger">必須</span> メイ(フリガナ)</label>
                        <%= f.text_field :first_name_kana, class: "form-control ", placeholder: "例:タロウ" %>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col">
                    <div class="form-group">
                        <label for="last_name_roman"><span class="badge badge-danger">必須</span> SEI(ローマ字)</label>
                        <%= f.text_field :last_name_roman, class: "form-control ", placeholder: "例:YAMADA" %>
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-group">
                        <label for="first_name_roman"><span class="badge badge-danger">必須</span> MEI(ローマ字)</label>
                        <%= f.text_field :first_name_roman, class: "form-control ", placeholder: "例:TARO" %>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                    <label for="postcode"><span class="badge badge-danger">必須</span> 郵便番号</label>
                    <%= f.text_field :postcode, class: "form-control ", placeholder: "例:1638001(-:ハイフン は不要です)" %>
                </div>
                <div class="form-group">
                    <label for="prefecture_code"><span class="badge badge-danger">必須</span> 都道府県</label>
                    <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name ,include_blank: '都道府県' %>
                </div>
                <div class="form-group">
                    <label for="address_city"><span class="badge badge-danger">必須</span> 住所(市町村区)</label>
                    <%= f.text_field :address_city, class: "form-control ", placeholder: "例:新宿区" %>
                </div>
                <div class="form-group">
                    <label for="address_street"><span class="badge badge-danger">必須</span> 住所(番地)</label>
                    <%= f.text_field :address_street, class: "form-control ", placeholder: "例:西新宿2-8-1" %>
                </div>
                <div class="form-group">
                    <label for="address_building"><span class="badge badge-primary">任意</span> 住所(ビル名・部屋番号)</label>
                    <%= f.text_field :address_building, class: "form-control ", placeholder: "例:都庁アパート302号室" %>
                </div>

                <div class="form-group">
                    <label for="nickname"><span class="badge badge-primary">任意</span> ニックネーム</label>
                    <%= f.text_field :nickname, class: "form-control ", placeholder: "全角で１０文字以内" %>
                </div>
                
                <%= f.submit "送信する" , class: "btn btn-primary"  %>
              <% end %>

app/views/users/edit.html.erb
    <div class="container">
        <div class="signup-header">
           <div class="row">
                    <h1>登録情報の更新</h1>
            </div>
        </div>
    </div>

    <hr class="signup-border">
    
    <div class="container">

    <%= render 'layouts/flash' %>
    
      <div class="row justify-content-md-center">
        
            <div class="col-10">
              <%= render 'form' %>
            </div>
      </div>
      <div class="row">
        <div class="col text-right"><%= link_to "マイページに戻る", user_path(current_user), class: "btn btn-secondary" %></div>
      </div>
    </div>

    <hr class="signup-border">

app/views/users/new.html.erb
    <div class="container">
        <div class="signup-header">
           <div class="row">
                    <h1>ユーザー登録</h1>
            </div>
        </div>
    </div>

    <hr class="signup-border">
    
    <div class="container">

    <%= render 'layouts/flash' %>
    
      <div class="row justify-content-md-center">
        
            <div class="col-10">
              <%= render 'form' %>
            </div>
      </div>
    </div>

    <hr class="signup-border">

app/views/users/show.html.erb
<br>
<br>
    <div class="container">
        <div class="mypage-header">
           <div class="row">
            <div class="col">
              <h1 class="text-left">マイページ</h1>
            </div>
            <div class="col text-right">
              <%= link_to "登録情報を編集する", edit_user_path(@user), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
    </div>

<hr class="mypage-border">
<br>
<br>

<div class="container">

  <%= render 'layouts/flash' %>

    <div class="row profile-box">
      <table class="table">
        <tr>
          <td>会員ID</td>
          <td><%= @user.account_id %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @user.fullname %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @user.fulladdress %></td>
        </tr>
        <tr>
          <td>ニックネーム</td>
          <td><%= @user.nickname %></td>
        </tr>
      </table>
    </div>
</div>

<br>
<br>

<hr class="mypage-border">

<br>
<br>

<div class="container">
  <div class="row">
    <h3>登録住所&nbsp;&nbsp;&nbsp;</h3>
    <%= link_to "一覧を見る", destinations_path, class: "btn btn-info" %>
  </div>
  <br>
  <div class="row">
    <h3>注文履歴&nbsp;&nbsp;&nbsp;</h3>
    <%= link_to "一覧を見る", orders_path, class: "btn btn-info" %>
  </div>
</div>
<br>
<br>