config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/user_guest', to: 'sessions#user_guest'
  post '/admin_guest', to: 'sessions#admin_guest'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :destinations, only: [:new, :index, :create, :edit, :update, :destroy]

  resources :cart_products, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      get :confirm
      get :thanks
    end
  end

  namespace :admin do
    get '/top', to: 'homes#top' 
    resources :products
    resources :users, only: [:index, :show, :edit, :update]
    patch '/admin/orders/:order_product_id', to: 'admin/orders#work_update'
    resources :orders,only: [:index, :show, :update] do
      member do
        patch :order_update
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  attr_accessor :radio_number, :destination_id

  belongs_to :user
  has_many :order_products

  enum payment_option: {
    bank_transfer: 1,
    credit_card: 2
  }

  enum order_status: {
    unpaid: 1,
    paid: 2,
    working: 3,
    ready: 4,
    shipped: 5
  }

  validates :user_id, presence: true
  
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :prefecture_code, presence: true
  validates :address_city, presence: true, length: {maximum: 15}
  validates :address_street, presence: true, length: {maximum: 30}
  validates :address_building, length: {maximum: 30}
  validates :receiver, presence: true, length: {maximum: 30}

  validates :payment_option, presence: true
  validates :status, presence: true
  validates :postage, presence: true
  validates :billing, presence: true

  def postcode_view
    self.postcode.to_s.insert(3, "-")
  end
  
  def fulladdress
    if self.address_building?
      "〒" + postcode_view + " " + prefecture_name + " " + address_city + " " + address_street + " " + address_building
    else
      "〒" + postcode_view + " " + prefecture_name + " " + address_city + " " + address_street
    end
  end

  def auto_update_work_status
    if self.status_before_type_cast == 2
      self.order_products.each do |op|
        op.update(work_status: 2)
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  include OrdersHelper

  def index
    params[:prev_path].nil? ? @prev_path = Rails.application.routes.recognize_path(request.referer) : @prev_path = params[:prev_path].permit!
    if params[:is_from_header].to_i == 1
      @orders = Order.all.order(created_at: "DESC")
    elsif
      if @prev_path[:controller] == "admin/homes"
        @orders = Order.where(created_at: Time.zone.today.all_day).order(created_at: "DESC")
      elsif @prev_path[:controller] == "admin/users"
        @user_id = params[:user_id]
        @orders = Order.where(user_id: params[:member_id]).order(created_at: "DESC")
      end
    else
      @orders = Order.all.order(created_at: "DESC")
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end
  
  def order_update
    @order = Order.find(params[:id])
    if  @order.update( params_int(order_params) )
      @order.auto_update_work_status
      flash[:success] = "注文ステータスの更新が完了しました"
      redirect_to admin_order_path(@order)
    else
      @order_products = @order.order_products
      flash.now[:danger] = "注文ステータスの更新に失敗しました"
      render action: :show
    end
  end

  def update
    @order_product = OrderProduct.find(params[:id])
    @order = Order.find(@order_product.order.id)
    if @order_product.update( params_int(order_product_params) )
      @order_product.auto_update_order_status
      flash[:success] = "商品別ステータスの更新が完了しました"
      redirect_to admin_order_path(@order)
    else
      @order_products = @order.order_products
      flash.now[:danger] = "商品別ステータスの更新に失敗しました"
      render action: :show
    end
  end
  
  private

  def order_params
    params.require(:order).permit(:status)
  end

  def order_product_params
    params.require(:order_product).permit(:work_status)
  end

  #数値に変換可能なparamsをintegerに変換してくれる
  def params_int(model_params)
    model_params.each do |key, value|
      if integer_string?(value)
        model_params[key]=value.to_i
      end
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :order_correct_user,   only: [:show]

  include OrdersHelper

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params_int(order_params))
    if @order.save
      @cart_products = CartProduct.where(user_id: current_user.id)
      @cart_products.each do |cart_product|
        @order_products = OrderProduct.create(
          product_id: cart_product.product.id,
          order_id: @order.id,
          price: cart_product.product.price,
          quantity: cart_product.quantity
          )
      end

      @cart_products.destroy_all

      case params[:order][:radio_number].to_i
        when 1
        when 2
        when 3
          @destination = Destination.create(
            user_id: current_user.id,
            receiver: params[:order][:receiver],
            postcode: params[:order][:postcode],
            prefecture_code: params[:order][:prefecture_code],
            address_city: params[:order][:address_city],
            address_street: params[:order][:address_street],
            address_building: params[:order][:address_building],
            )
      end
      redirect_to thanks_orders_url
    else
      flash.now[:danger] = '購入に失敗しました'
      @cart_products = CartProduct.where(user_id: current_user.id)
      @postage = 800
      render :confirm
    end
  end
  
  def confirm
    
    @cart_products = CartProduct.where(user_id: current_user.id)
    @postage = 800

    if params[:order][:payment_option].nil?
      params[:order][:payment_option] =
      case params[:order][:radio_number].to_i
      when 1
        destination_when1
      when 2
        destination_when2
      when 3
        destination_when3
      when 0
        destination_when0
      end
      # @order.valid?
      flash.now[:danger] = '支払い方法が選択されていません'
      render action: :new
    else
      case params[:order][:radio_number].to_i
      when 1
        destination_when1
        @order.payment_option = params[:order][:payment_option].to_i
        @order.radio_number = params[:order][:radio_number].to_i
      when 2
        destination_when2
        @order.payment_option = params[:order][:payment_option].to_i
        @order.radio_number = params[:order][:radio_number].to_i
      when 3
        destination_when3
        @order.payment_option = params[:order][:payment_option].to_i
        @order.radio_number = params[:order][:radio_number].to_i
      when 0
        destination_when0
      end

      if params[:order][:radio_number].nil?
        flash.now[:danger] = '配送先が選択されていません'
        render action: :new
      end
    end
  end

  def thanks
    
  end

  def index
    @orders = Order.where(user_id: current_user.id).order(created_at: "DESC").all
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

  private

  def order_correct_user
    @order = current_user.orders.find_by(id: params[:id])
    redirect_to root_url if @order.nil?
  end

  def destination_when1
    ##自分の住所
    @order = Order.new(
    user_id: current_user.id,
    receiver: current_user.fullname,
    postcode: current_user.postcode,
    prefecture_code: current_user.prefecture_code,
    address_city: current_user.address_city,
    address_street: current_user.address_street,
    address_building: current_user.address_building,
    billing: @cart_products.map{ |cp| (cp.product.price_tax*cp.quantity) }.sum.round + @postage
    )
  end

  def destination_when2
    ##登録された住所から選択
    destination = Destination.find(params[:order][:destination_id])
    @order = Order.new(
      user_id: current_user.id,
      receiver: destination.receiver,
      postcode: destination.postcode,
      prefecture_code: destination.prefecture_code,
      address_city: destination.address_city,
      address_street: destination.address_street,
      address_building: destination.address_building,
      billing: @cart_products.map{ |cp| (cp.product.price_tax*cp.quantity) }.sum.round + @postage
    )
  end

  def destination_when3
    ##新規作成の住所
    @order = Order.new(
      user_id: current_user.id,
      receiver: params[:order][:receiver],
      postcode: params[:order][:postcode],
      prefecture_code: params[:order][:prefecture_code],
      address_city: params[:order][:address_city],
      address_street: params[:order][:address_street],
      address_building: params[:order][:address_building],
      billing: @cart_products.map{ |cp| (cp.product.price_tax*cp.quantity) }.sum.round + @postage
      )
  end

  def destination_when0
    @order = Order.new(
      user_id: current_user.id,
      billing: @cart_products.map{ |cp| (cp.product.price_tax*cp.quantity) }.sum.round + @postage
      )
  end

  def order_params
    params.require(:order).permit(:user_id, :receiver,
       :postcode, :prefecture_code, :address_city, :address_street, :address_building,
        :payment_option, :status, :postage, :billing, :destination_id, :radio_number)
  end
  
  #数値に変換可能なparamsをintegerに変換してくれる(helperに変更可能か確認するメソッドを定義)
  def params_int(model_params)
    model_params.each do |key, value|
      if integer_string?(value)
        model_params[key]=value.to_i
      end
    end
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  #数値に変換可能かを確認
  def integer_string?(str)
    Integer(str)
    true
  rescue ArgumentError
    false
 end

end

app/views/orders/confirm.html.erb
<div class="container">

<%= render 'layouts/flash' %>

  <br>
  <br>
  <div class="row">
    <div class="col-12">
      <h1>注文情報確認</h1>
    </div>
  </div>
  <br>
  <br>

  <div class="row">
    <div class="col-12">
      <table class="table table-hover table-borderd">
        <thead>
          <tr class="active">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_products.each do |cart_product| %>
            <tr>
              <td>
                <%= image_tag cart_product.product.image.url, :size => "100x75", class: "top-image" %>
                <%= cart_product.product.name %>
              </td>
              <td><%= number_to_currency(cart_product.product.price_tax, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
              <td><%= cart_product.quantity %></td>
              <td><%= number_to_currency(cart_product.product.price_tax*cart_product.quantity, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-12">
      <table class="table table-hover table-bordered">
        <tbody>
          <tr>
            <th>送料</th>
            <td><%= number_to_currency(@postage, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
          </tr>
          <tr>
            <th>商品合計</th>
            <td><%= number_to_currency(@cart_products.map{ |cp| (cp.product.price_tax*cp.quantity).round }.sum, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td><%= number_to_currency(@cart_products.map{ |cp| (cp.product.price_tax*cp.quantity).round }.sum + @postage, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-12">
      <table class="table table-hover table-bordered">
        <tr>
          <th>お支払い方法</th>
          <td>
            <% case @order.payment_option %>
            <% when "credit_card" %>
              <%= "クレジットカード" %>
            <% when "bank_transfer" %>
              <%= "銀行振込" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>お届け先</th>
          <td><%= @order.fulladdress %></td>
        </tr>
      </table>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-12">
      <%= form_for(@order, url:orders_path) do |f| %>
        <%#= render 'shared/error_messages', object: f.object %>

          <%= f.hidden_field :user_id, :value => current_user.id %>
          <!--支払い方法-->
          <%= f.hidden_field :payment_option, :value => @order.payment_option %>
          <!--お届け先-->
          <%= f.hidden_field :postcode, :value =>  @order.postcode.delete("^0-9") %>
          <%= f.hidden_field :prefecture_code, :value =>  @order.prefecture_code %>
          <%= f.hidden_field :address_city, :value =>  @order.address_city %>
          <%= f.hidden_field :address_street, :value =>  @order.address_street %>
          <%= f.hidden_field :address_building, :value =>  @order.address_building %>
          <%= f.hidden_field :receiver, :value =>  @order.receiver %>
          <!--送料、請求金額-->
          <%= f.hidden_field :postage, :value => @postage %>
          <%= f.hidden_field :billing, :value => @cart_products.map{ |cp| (cp.product.price_tax*cp.quantity) }.sum.round + @postage %>

          <%= f.hidden_field :radio_number, :value =>@order.radio_number %>
          <!--ボタン-->
          <div class="text-right">
            <span><%= f.submit "注文を確定する", class: "btn btn-success btn-lg" %></span>
          </div>
          <div class="text-left">
            <span><%= link_to ">>お支払い方法・お届け先の選択に戻る", new_order_path, class: "h6" %></span>
          </div>
      <% end %>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/orders/index.html.erb
<br>
<br>
<br>

<div class="container">
  <div class="mypage-header">
    <div class="row">
      <div class="col">
        <h1 class="text-left">注文履歴一覧</h1>
      </div>
    </div>
  </div>
</div>

<hr class="mypage-border">

<div class="container">

<%= render 'layouts/flash' %>



  <br>
  <br>
  <br>



<% if current_user.orders.present? %>

  <div class="row">
    <div class="col-12">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= order.fulladdress %></td>
              <td>
                <% order.order_products.each do |op| %>
                  <%= op.product.name %><br>
                <% end %>
              </td>
              <td><%= number_to_currency(order.billing, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
              <td>
                <% case order.status %>
                  <% when 1 %>
                  <%= "入金待ち" %>
                  <% when 2 %>
                  <%= "入金確認" %>
                  <% when 3 %>
                  <%= "製作中" %>
                  <% when 4 %>
                  <%= "発送準備中" %>
                  <% when 5 %>
                  <%= "発送済み" %>
                <% end %>
              </td>
              <td><%= link_to "表示する", order_path(order.id), class: "btn btn-primary btn-block" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<% else %>

  <div class="row">
    <div class="col-12">
      <div class="text-center"><%= link_to "まだ注文はありません！お買い物を楽しみましょう!", products_path, class: "btn btn-info" %></div>
    </div>
  </div>

<% end %>


  <br>
  <br>
  <br>

  <div class="row">
    <%= link_to "買い物を続ける", products_path, class: "btn btn-info" %>
  </div>
  <br>
  <div class="row">
    <%= link_to "マイページに戻る", user_path(current_user), class: "btn btn-info" %>
  </div>

  <br>
  <br>
  <br>

</div>

<hr class="mypage-border">

<br>
<br>
<br>

app/views/orders/new.html.erb
<div class="container">

  <br>
  <div class="row mypage-header">
    <h1>注文情報入力</h1>
  </div>
  <br>
</div>

<hr class="mypage-border">

<br>
<br>

<div class="container">

<%= render "layouts/flash" %>

  <div class="row">
    <div class="col-12" role="form">
      <%= form_for @order, url: confirm_orders_path, method: :get do |f| %>
        <div class="form-group row">
          <div class="col-7">
            <h2 class="text-success">支払い方法</h2>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-10 justify-content-md-center">
            <%= f.radio_button :payment_option, 2 %>
            <%= f.label :payment_option, "クレジットカード", value: 2, style: "display: inline-block;" %>
            <br>
            <%= f.radio_button :payment_option, 1 %>
            <%= f.label :payment_option, "銀行振込", value: 1, style: "display: inline-block;" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-7">
            <h2 class="text-success">お届け先</h2>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-10 justify-content-md-center">
            <%= f.radio_button :radio_number, 1 %>
            <%= f.label :radio_number, "ご自身の住所", value: 1, style: "display: inline-block;" %><br>
            <%= current_user.fulladdress %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-10 justify-content-md-center">
            <%= f.radio_button :radio_number, 2 %>
            <%= f.label :radio_number, "登録先住所から選択", value: 2, style: "display: inline-block;" %><br>
            <%= f.collection_select :destination_id, Destination.where(user_id: current_user.id), :id , :fulladdress, form: "new_order" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-10 justify-content-md-center">
            <%= f.radio_button :radio_number, 3 %>
            <%= f.label :radio_number, "新しいお届け先", value: 3, style: "display: inline-block;" %><br>
            <%= f.label :postcode, "郵便番号(ハイフンなし)" %>
            <%= f.text_field :postcode, class: "form-control ", placeholder: "例:1638001(-:ハイフン は不要です)" %><br>
            <%= f.label :prefecture_code, "都道府県" %>
            <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name ,include_blank: '都道府県' %><br>
            <%= f.label :address_city, "市町村区" %>
            <%= f.text_field :address_city, class: "form-control ", placeholder: "例:新宿区" %><br>
            <%= f.label :address_street, "番地" %>
            <%= f.text_field :address_street, class: "form-control ", placeholder: "例:西新宿2-8-1" %><br>
            <%= f.label :receiver, "ビル名・部屋番号(任意)" %>
            <%= f.text_field :address_building, class: "form-control ", placeholder: "例:都庁アパート302号室" %><br>
            <%= f.label :receiver, "宛名" %>
            <%= f.text_field :receiver, class: "form-control ", placeholder: "例:山田太郎" %>
          </div>
        </div>


        <div class="form-group row">
          <div class="col-10 justify-content-md-center">
            <span><%= f.submit "確認画面へ進む", class: "btn btn-primary" %></span>
            <span><%= link_to "カートに戻る", cart_products_path, class: "btn btn-secondary" %></span>
          </div>
        </div>


      <% end %>
    </div>
  </div>
</div>

<hr class="mypage-border">

<br>
<br>
<br>

app/views/orders/show.html.erb
<div class="container">

<% render 'layouts/flash'%>
  <br>
  <br>
  <br>

  <div class="row">
    <h1>注文履歴詳細</h1>
  </div>

  <br>
  <br>
  <br>

  <div class="row">
    <div class="col-12">
      <h4>注文内容</h4>
      <br>
      <br>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>商品</th>
            <th>単価</th>
            <th>個数</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order_products.each do |op| %>
            <tr>
              <td><%= op.product.name %></td>
              <td><%= number_to_currency(op.price_tax, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
              <td><%= op.quantity %></td>
              <td><%= number_to_currency(op.subtotal, :format => "%u%n", :unit => "￥", :precision => 0) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br>
  <br>
  <br>

  <div class="row">
    <div class="col-7">
      <h4>注文情報</h4>
      <br>
      <br>
      <table class="table table-hover table-bordered">
        <tbody>
          <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d')  %></td>
          </tr>
          <tr>
            <td>配送先</td>
            <td><%= @order.fulladdress  %></td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td>
              <% case @order.payment_option %>
              <% when "bank_transfer" %>
                <%= "銀行振込" %>
              <% when "credit_card" %>
                <%= "クレジットカード" %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>ステータス</td>
            <td>
              <% case @order.status %>
              <% when 1 %>
                <%= "入金待ち" %>
              <% when 2 %>
                <%= "入金確認" %>
              <% when 3 %>
                <%= "制作中" %>
              <% when 4 %>
                <%= "発送準備中" %>
              <% when 5 %>
                <%= "発送済み" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-5">
      <h4>請求情報</h4>
      <br>
      <br>
      <table class="table table-hover table-bordered">
        <tbody>
          <tr>
            <td>商品合計</td>
            <td>
              <%= number_to_currency(@order.billing - @order.postage, :format => "%u%n", :unit => "￥", :precision => 0) %>
            </td>
          </tr>
          <tr>
            <td>配送料</td>
            <td>
              <%= number_to_currency(@order.postage, :format => "%u%n", :unit => "￥", :precision => 0) %>
            </td>
          </tr>
          <tr>
            <td>請求金額</td>
            <td>
              <%= number_to_currency(@order.billing, :format => "%u%n", :unit => "￥", :precision => 0) %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <br>
  <br>
  <br>

  <div class="row">
    <%= link_to "注文履歴一覧に戻る", orders_path, class: "btn btn-info" %>
  </div>

  <br>
  <br>
  <br>

</div>

app/views/orders/thanks.html.erb
<br>
<br>
<br>

<hr class="signup-border">

<br>
<br>
<br>
<br>
<br>

<div class="container">

<%= render 'layouts/flash' %>

  <div class="row">
    <div class="col-8 justify-content-center">
      <h1 class="text-left"><strong>ご購入ありがとうございました！</strong></h1>
      <br>
      <br>
      <h1 class="text-left"><strong>引き続きONK Shoppingをお楽しみ下さい！</strong></h1>
      <br>
      <br>
      <%= link_to "買い物を続ける", products_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>

<hr class="signup-border">

<br>
<br>
<br>