config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/user_guest', to: 'sessions#user_guest'
  post '/admin_guest', to: 'sessions#admin_guest'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :destinations, only: [:new, :index, :create, :edit, :update, :destroy]

  resources :cart_products, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      get :confirm
      get :thanks
    end
  end

  namespace :admin do
    get '/top', to: 'homes#top' 
    resources :products
    resources :users, only: [:index, :show, :edit, :update]
    patch '/admin/orders/:order_product_id', to: 'admin/orders#work_update'
    resources :orders,only: [:index, :show, :update] do
      member do
        patch :order_update
      end
    end
  end
end

app/views/layouts/_admin_footer.html.erb
<footer class="page-footer font-small pt-4 bg-dark">
  <div class="container text-center text-md-left text-white">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">株式会社オニキ商事</h5>
        <p>「日本の楽しい・美しい・美味しいを届ける」をスローガンに<br>
        ECサイトONK SHOPPINGを運営しています</p>
      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
    </div>
  </div>
  <div class="footer-copyright text-center py-3 text-white">© 2020 Copyright:
    <%= link_to 'ONK Shopping', admin_top_path %>
  </div>
</footer>

app/views/layouts/_admin_header.html.erb
<header class="blog-header py-3 bg-dark" >
  <div class="container">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <%= link_to 'ONK SHOPPING(管理者版)', admin_top_path, class: "text-white" %>
      </div>
      <div class="col-8 d-flex justify-content-end align-items-center">
          <%= link_to '会員情報一覧', admin_users_path, class: 'btn btn-sm btn-secondary' %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-sm btn-outline-secondary text-white' %>
      </div>
    </div>
  </div>
</header>

<div class="nav-scroller py-1 mb-2 bg-dark">
  <div class="container">
  <nav class="navbar">
    <form class="form-inline">
      <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->
      <!-- <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button> -->
    </form>
    <div class="justify-content-end">
      <%= link_to '商品一覧', admin_products_path, class: "p-2 text-white justify-content-end" %>
      <%= link_to '注文一覧', admin_orders_path, class: "p-2 text-white justify-content-end" %>
    </div>
  </nav>
  </div>
</div>

app/views/layouts/_flash.html.erb
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small pt-4" style="background-color: #eae6e4;">
  <div class="container text-center text-md-left">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">株式会社オニキ商事</h5>
        <p>「日本の楽しい・美しい・美味しいを届ける」をスローガンに<br>
        ECサイトONK SHOPPINGを運営しています</p>
      </div>

      <hr class="clearfix w-100 d-md-none pb-3">


      <div class="col-md-3 mb-md-0 mb-3">

      </div>

      <div class="col-md-3 mb-md-0 mb-3">

      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <%= link_to 'ONK Shopping', root_path %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="blog-header py-3" style="background-color: #eae6e4;">
  <div class="container">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <%= link_to 'ONK SHOPPING', root_path, class: "text-muted" %>
      </div>
      <div class="col-8 d-flex justify-content-end align-items-center">
        <% if logged_in? %>
          <%= link_to 'マイページ', user_path(current_user), class: 'btn btn-sm btn-secondary' %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-sm btn-outline-secondary' %>
        <% else %>
          <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-sm btn-secondary' %>
          <%= link_to 'ログイン', login_path, class: 'btn btn-sm btn-outline-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</header>

<div class="nav-scroller py-1 mb-2" style="background-color: #eae6e4;">
<div class="container">
  <nav class="navbar">
    <form class="form-inline">
      <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->
      <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
    </form>
    <div class="justify-content-end">
      <%= link_to '商品一覧', products_path, class: "p-2 text-muted justify-content-end" %>
      <%= link_to 'カート', cart_products_path, class: "p-2 text-muted justify-content-end" %>
    </div>
  </nav>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcOniki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if logged_in? && current_user.admin? %>
      <%= render 'layouts/admin_header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>

    <%= yield %>

    <% if logged_in? && current_user.admin? %>
      <%= render 'layouts/admin_footer' %>
    <% else %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>